### PR TITLE
Added Ali Baba's page

### PR DESCRIPTION
**Pull request by deadion2ttip**
Added the Address and a note.

Dylan Morosini & Chris Griffin

### CODE REVIEW

**Comment by alexch** [comment]
Please do some Googling or phone calling and find out the opening/closing hours

**Comment by Dangeranger** [comment]
@deadion2ttip 

Nice work, but can you merge my changes into this from https://github.com/BurlingtonCodeAcademy/yelpington/pull/2 ?

**Comment by deadion2ttip** [comment]
@alexch Can do!
@Dangeranger I could, How would I do that?

**Comment by alexch** [comment]
oops, nevermind about the hours

the name is wrong though -- it has an H in it

**Comment by Dangeranger** [comment]
@deadion2ttip 

Sure. What I would recommend: 
- rename your file name to `ali-babas-kabob-shop.md`  
- merge the contents of the files on your local repository
- push the changes to your remote fork

After that the PR will update with the changes.

Good luck!

**Comment by alexch** [comment]
Great! Thanks. 🐱 💯 
ship it

**Pull request merged**
