### PR TITLE
Kountry kart deli

### PR DESCRIPTION
**Pull request by jakegoss**
Jake G and Dylan F

### CODE REVIEW

**Comment by JuliaKan** [comment]
Hey, I'd love some more information regarding hours and food type/menu. Do you have any recommendations? Thanks.

**Comment by alexch** [comment]
it's missing some info; let me know if you want to keep editing it or if I should merge it as is

**Comment by dfree08** [comment]
Hi Alex, we are going to edit and make a new pull request. Thanks

**Comment by alexch** [comment]
closed as per https://github.com/BurlingtonCodeAcademy/yelpington/pull/12#issuecomment-395806379

**Pull request closed without merging**
