### PR TITLE
Mr. Mikes

### PR DESCRIPTION
**Pull request by jakedurell**
# **_Oh man, we forgot the hours..._**

### CODE REVIEW

**Comment by alexch** [comment]
yes you did :-)

Also please look up on the wall and put the phone number in standard format.

**Comment by alexch** [comment]
then call the phone number and ask for its hours

**Comment by alexch** [comment]
OH ALSO... it's spelled with an H ... AHLI BABAS not ALI BABAS. Please rename the file.

**Comment by Dangeranger** [comment]
@jakedurell 

Hey it looks like you need to change the file name to the format defined in the instructions. 
i.e. You have ` MrMikes.md` and we need `mr-mikes`.

**Comment by jakedurell** [comment]
@alexch our MD is not Ahli Baba's. ???

**Comment by alexch** [comment]
Nevermind the "ali baba" comment -- I was confused. 
But mr-mikes.md has some formatting issues. Please follow the style guide in http://bootcamp.burlingtoncodeacademy.com/projects/yelpington

**Comment by jakedurell** [comment]
Updates added. I think I addressed all formatting issues mentioned by @alexch.

**Pull request merged**
